### ISSUE TITLE
LEGO EV3 classroom download recipe fails code signature verification

### ISSUE THREAD

**Issue by sincerelyjoshin** [autopkg/nstrauss-recipes#10]
It appears LEGO has modified the identifier from "com.lego.ev3" to "com.lego.ev3.edu"

`
identifier "com.lego.ev3.edu" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = RS3Y27K2T9
`

**Comment by nstrauss** [comment]
Thanks for report. Fixed in 2bb0d34f1e1f2e995cfdb636594ef4bafe950206
