### ISSUE TITLE
Google Earth Pro URL change

### ISSUE THREAD

**Issue by mrowell** [autopkg/nstrauss-recipes#11]
The Google Earth Pro URL for the latest release has changed (note added rel="noopener")
`<a href="https://dl.google.com/dl/earth/client/advanced/current/googleearthpromac-intel-7.3.3.dmg" rel="noopener">v7.3.3 for Mac</a>`

Previously:
`<a href="https://dl.google.com/dl/earth/client/advanced/current/googleearthpromac-intel-7.3.2.dmg">v7.3.2 for Mac</a>`

The current regex pattern is skipping the latest version because of the `rel="noopener"` attribute. 

The Pattern could be changed from:
 ```
       <key>RE_PATTERN</key>
        <string>&lt;a href=&quot;(?P&lt;url&gt;https:\/\/.*\/googleearthpromac.*\.dmg)&quot;&gt;</string>

```
To:
  ```
      <key>RE_PATTERN</key>
        <string>&lt;a href=&quot;(?P&lt;url&gt;https:\/\/.*\/googleearthpromac.*\.dmg)&quot;</string>
```

**Comment by nstrauss** [comment]
Thanks for the report. Regex has been updated to reflect your suggested change. 

New version also comes with a new developer ID used to sign the package. Updated both and recipes should be working as expected with 76b1dcd34a8548e9a55e52685a36030f3150ce9e
