### ISSUE TITLE
Cricut Design Space Failed to Find Cricut Version or URL

### ISSUE THREAD

**Issue by killer23d** [autopkg/nstrauss-recipes#17]
An error message with Cricut Design Space recipe showed up an error:

"Unable to find Cricut version or URL. Failed."

Seems like they have changed the URL for parsing.

**Comment by killer23d** [comment]
The current version of the app is being downloaded from here instead
https://staticcontent.cricut.com/a/software/osx-native/Cricut%20Design%20Space%20Install%20v6.6.134.dmg

**Comment by nstrauss** [comment]
Hi @killer23d Yes, been broken for a few days now. Need to find where their XML feed has been moved. http://staticcontent.cricut.com/ is where I was pulling the version from to construct the download URL, but that no longer exists. Will need to do some more research. If you find it yourself before me please let me know.

**Comment by nstrauss** [comment]
@killer23d This has been resolved with commit 3331351f065554ad0c487ba2cb128cce4604dd7a. I was able to parse the latest version through their publicly available JSON. https://s3-us-west-2.amazonaws.com/staticcontent.cricut.com/a/software/osx-native/latest.json
