### ISSUE TITLE
Google Drive is on v. 47 now

### ISSUE THREAD

**Issue by sau70networkadmin** [autopkg/nstrauss-recipes#18]
Apologies if this is not your issue...but I have clients whose Google Drive.app has self-updated to 47 but AutoPkg/Munki still think 46.0.3 is the latest. THANK YOU!

**Comment by nstrauss** [comment]
Hey @sau70networkadmin Google only gives us access to the direct download version. They will start to roll out new versions before updating the direct download URL. Not much I can do that about. I do have a feature request submitted for Google to more quickly provide the latest version via direct download as well as beta/Canary pre-release. https://www.cloudconnectcommunity.com/ccc/ls/community/googleworkspace-feature-ideas/post/4892573596778496

https://dl.google.com/drive-file-stream/beta47/GoogleDrive.dmg has the v47 beta, but I don't know if there's a place to parse the latest version to automate with autopkg. Going to close this issue as there's not much I can do until Google makes changes.
