### ISSUE TITLE
OBS package recipe now grabs the wrong key from the info.plist

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/nstrauss-recipes#31]
This is currently configured to pull the `CFBundleVersion` from the info.plist. On the latest release (v28.0.0) this is `2966436867`.
The key needed looks to be `CFBundleShortVersionString` which is now `28.0.0`.

PR incoming!

**Comment by Daz-wallace** [comment]
Oh and now the version splitter will also not be needed

**Comment by Daz-wallace** [comment]
PR logged as #32

**Comment by nstrauss** [comment]
Thanks for filing an issued. Closed with your PR https://github.com/autopkg/nstrauss-recipes/pull/32
