### ISSUE TITLE
Google Drive pkg recipe not working

### ISSUE THREAD

**Issue by dbmann89** [autopkg/nstrauss-recipes#37]
Hello,

Getting this error running the Google Drive pkg recipe:

Error in com.github.nstrauss.pkg.GoogleDrive: Processor: PkgPayloadUnpacker: Error: extraction of /Users/redacted/Library/AutoPkg/Cache/com.github.nstrauss.pkg.GoogleDrive/unpack/GoogleDrive_x86_64.pkg/Payload with ditto failed: ditto: cpio read error: bad file format

Tried on two machines so seems like it is not working.

**Comment by mikaellofgren** [comment]
I got the same problem here, it looks like the payload has changed format from `gzip` to `pbzx`
Previous version 66.0.3
```
file
GoogleDrive_x86_64.pkg/Payload: gzip compressed data, from Unix, original size modulo 2^32 409135104
```

Latest version 67.0.2
```
file
/GoogleDrive_x86_64.pkg/Payload: data
```
seems to be pbzx format

Running ditto on newer version (same as  PkgPayloadUnpacker using) gives this error, but works fine on older version.
```
/usr/bin/ditto -x -z /GoogleDrive_x86_64.pkg/Payload /tmp/payload
ditto: cpio read error: bad file format
```

**Comment by nstrauss** [comment]
@dbmann89 @mikaellofgren Commit https://github.com/autopkg/nstrauss-recipes/commit/165c72f31c616443c7d90f2be336014f2aa48edf should fix this. Using `aa` over `ditto` to support the new file format. Please `autokpg repo-update nstrauss-recipes` and try again.

**Comment by mikaellofgren** [comment]
Works great, thanks for the fast fix!
