### ISSUE TITLE
GoProQuik - Expired Certificate.

### ISSUE THREAD

**Issue by paul-cossey** [autopkg/nstrauss-recipes#45]
Hi, @nstrauss 

The GoProQuick download recipe is currently failing with this error.
```
Processor: CodeSignatureVerifier: Error: Code signature verification failed. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
```

The certificate on the package expired yesterday. 
![Screenshot 2023-03-02 at 11 38 37](https://user-images.githubusercontent.com/16046272/222419072-5acc12d1-7560-4e9b-ad6d-8db82b9386fc.png)

Maybe this is because it's no longer supported/discontinued by the vendor? All I can see reference to here https://gopro.com/en/us/shop/quik-app-video-photo-editor is iPhone or iPad app.

**Comment by paul-cossey** [comment]
Bit more digging, I can see it's now classed as legacy software: https://community.gopro.com/s/article/GoPro-legacy-software?language=en_US

**Comment by paul-cossey** [comment]
I'm not sure the installer would even run with an expired cert?

But tbh I think if it were one of our recipes I'd deprecate it. We'll be removing it from our repo so won't have a need for it going forward.

**Comment by nstrauss** [comment]
Deprecation warning added! https://github.com/autopkg/nstrauss-recipes/commit/95a9d9b4045fef400e2ba606004e0132fd6a421f
