### ISSUE TITLE
SimpleJSONParser Error

### ISSUE THREAD

**Issue by dbmann89** [autopkg/nstrauss-recipes#47]
Hello,

I am getting this error when running this recipe:

```
Expecting value: line 1 column 1 (char 0)
Failed.

The following recipes failed:
    cricutdesignspace.pkg
        Error in com.github.nstrauss.pkg.CricutDesignSpace: Processor: SimpleJSONParser: Error: Expecting value: line 1 column 1 (char 0)

Nothing downloaded, packaged or imported.
```

Thanks!

**Comment by killer23d** [comment]
I also observe the same behavior on my end. I think it has to do with the new site design.

Expecting value: line 1 column 1 (char 0)

**Comment by nstrauss** [comment]
@dbmann89 @killer23d Thanks for reporting. Fixed in https://github.com/autopkg/nstrauss-recipes/pull/48.
