### ISSUE TITLE
x86 to x64 in /exacqVision.download.recipe

### ISSUE THREAD

**Issue by rmckellar** [autopkg/nstrauss-recipes#54]
For the ARCHITECTURE key, it's stated that x86 (or arm64) should be used. However, the actual download URL uses x64 (instead or x86).

**Comment by nstrauss** [comment]
I definitely, 100% tested this. 😅 Fixed in https://github.com/autopkg/nstrauss-recipes/commit/07996dc6f44d1dc10c98f911eeb05f482216b9e7.

**Comment by rmckellar** [comment]
I'm very willing to bet the company changed the URL, haha! 😋
