### ISSUE TITLE
Autodesk Fusion 360 - New download URL

### ISSUE THREAD

**Issue by joshnovotny** [autopkg/nstrauss-recipes#63]
Looks like Autodesk dropped the 360 from the download URL for reasons?

Error in com.github.nstrauss.pkg.AutodeskFusion360: Processor: URLDownloader: Error: curl: (22) The requested URL returned error: 403

New URL:

https://dl.appstreaming.autodesk.com/production/installers/Autodesk%20Fusion%20Admin%20Install.pkg

**Comment by nstrauss** [comment]
@joshnovotny Here you go https://github.com/autopkg/nstrauss-recipes/pull/64 Thanks for finding the updated URL.
