### ISSUE TITLE
OBS download - platform names have changed case

### ISSUE THREAD

**Issue by robertryansqub** [autopkg/nstrauss-recipes#68]
The OBS download recipe needs an update as the download links have changed to be all lowercase, eg:

https://cdn-fastly.obsproject.com/downloads/obs-studio-30.1.1-macos-intel.dmg
https://cdn-fastly.obsproject.com/downloads/obs-studio-30.1.1-macos-apple.dmg

This can be addressed in the overrides, of course, but this may confuse people.

**Comment by nstrauss** [comment]
@robertryansqub Thanks for reporting. Fixed in 6e9cf31179f3b7d341d4e71272be21cfd76bd97c
