### ISSUE TITLE
Camtasia - CodeSignatureVerifier

### ISSUE THREAD

**Issue by joshnovotny** [autopkg/nstrauss-recipes#75]
Code signature verification failed. Note that all verifications can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
Failed.

The following recipes failed:
    camtasia.pkg
        Error in com.github.nstrauss.pkg.Camtasia: Processor: CodeSignatureVerifier: Error: Code signature verification failed. Note that all verifications can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.

New version just came out in the past few days.

**Comment by nstrauss** [comment]
@joshnovotny My pkg recipe uses https://github.com/autopkg/jps3-recipes/blob/master/Camtasia/Camtasia.download.recipe as a parent recipe. New value should be...
```
identifier "com.techsmith.camtasia2024" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "7TQL462TU8"
```
PR created https://github.com/autopkg/jps3-recipes/pull/104
