### ISSUE TITLE
Cricut Design Space Beta Completed

### ISSUE THREAD

**Issue by killer23d** [autopkg/nstrauss-recipes#8]
Cricut Design Space has updated the app to full release.

https://design.cricut.com/#/launcher

The current recipes for both the web plugin and beta app are failing:

RECIPE | MESSAGE
-- | --
local.pkg.CricutDesignSpaceBeta | Error in local.pkg.CricutDesignSpaceBeta: Processor: URLTextSearcher: Error: No match found on URL: https://design-beta2.cricut.com/main.a47411fe2a2e03bcdf59.js

**Comment by nstrauss** [comment]
Thanks for letting me know. Will need to retire plugin recipe and rework recipe desktop Design Space app. 

Best I can find right now is releases listed at http://staticcontent.cricut.com/. Think I'd have to write a custom processor to parse the latest version. Happy to accept PRs. 😃

**Comment by nstrauss** [comment]
@killer23d New custom processor written to account for changes. Tested under autopkg 1.4.1 and 2.0.1 RC. Closing this issue.

Beta recipes retired/deleted. Deleted old references to postinstall scripts for the Bitrock installer with the plug-in version. Only existing recipes are the new, working ones.
