### ISSUE TITLE
NWEA Secure Browser- New download URL

### ISSUE THREAD

**Issue by someonecleverlyamusing** [autopkg/nstrauss-recipes#85]
New url is: https://cdn.nwea.org/docs/NWEA-Secure-Testing-Browser-Mac.dmg

The old url still works, but downloads an outdated version.

**Comment by nstrauss** [comment]
@someonecleverlyamusing Thanks for reporting. Fixed in https://github.com/autopkg/nstrauss-recipes/pull/86
